FROM python:3.8

EXPOSE 8501

WORKDIR /app
COPY ./app/requirements.txt .

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

COPY ./app/app.py ./
COPY ./utils.py ./

RUN wget https://github.com/edbons/faiky-tails/releases/download/v0.1.0/onnx_model_tokenizer.zip
RUN unzip -o -q onnx_model_tokenizer.zip

ENTRYPOINT [ "streamlit", "run"]
CMD ["./app.py"]