FROM python:3.8

EXPOSE 8501

WORKDIR /app
COPY ./app/requirements.txt .

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

COPY ./app/app.py ./

ENTRYPOINT [ "streamlit", "run"]
CMD ["./app.py"]